"use client";
import { useState } from "react";
import { useLang } from "@/lib/LanguageContext";

const charts = [
  { file: "/visuals/01-portfolio-optimizer.png", label: "Portfolio Optimizer — Efficient Frontier", labelFr: "Optimiseur — Frontière Efficiente" },
  { file: "/visuals/02-lbo-model.png", label: "LBO Model — Waterfall & IRR Sensitivity", labelFr: "LBO — Cascade & Sensibilité IRR" },
  { file: "/visuals/03-dcf-engine.png", label: "DCF Engine — Football Field Valuation", labelFr: "DCF — Valorisation Football Field" },
  { file: "/visuals/04-var-dashboard.png", label: "VaR Dashboard — Loss Distribution", labelFr: "VaR — Distribution des pertes" },
  { file: "/visuals/05-esg-tool.png", label: "ESG Tool — Radar Comparison", labelFr: "ESG — Comparaison Radar" },
  { file: "/visuals/06-credit-dashboard.png", label: "Credit Dashboard — Altman Z-Score", labelFr: "Crédit — Z-Score Altman" },
];

export default function Gallery() {
  const [selected, setSelected] = useState<number | null>(null);
  const { lang } = useLang();
  const isFr = lang === "fr";

  return (
    <section id="gallery" className="max-w-4xl mx-auto px-8 py-16">
      <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: "1.3rem", fontWeight: 400, lineHeight: 1.3, letterSpacing: "-0.01em", color: "#1a1a1a", marginBottom: "2.5rem" }}>
        {isFr ? "Sorties visuelles" : "Visual Outputs"}
      </h2>
      <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.85rem", fontWeight: 300, color: "#888", marginBottom: "2rem", lineHeight: 1.7 }}>
        {isFr
          ? "Outputs réels générés par les outils Python — chaque graphique correspond à un projet de la liste ci-dessus."
          : "Real outputs generated by the Python tools — each chart corresponds to a project from the list above."}
      </p>

      {/* Grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "0.75rem" }}>
        {charts.map((c, i) => (
          <div key={i} onClick={() => setSelected(i)} style={{ cursor: "pointer", position: "relative" }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={c.file} alt={isFr ? c.labelFr : c.label}
              style={{ width: "100%", height: "auto", display: "block", filter: "grayscale(8%)" }}
              onMouseEnter={e => { (e.currentTarget as HTMLImageElement).style.opacity = "0.85"; }}
              onMouseLeave={e => { (e.currentTarget as HTMLImageElement).style.opacity = "1"; }}
            />
            <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.68rem", fontWeight: 300, color: "#aaa", marginTop: "0.5rem", letterSpacing: "0.04em" }}>
              {isFr ? c.labelFr : c.label}
            </p>
          </div>
        ))}
      </div>

      {/* Lightbox */}
      {selected !== null && (
        <div onClick={() => setSelected(null)}
          style={{ position: "fixed", inset: 0, background: "rgba(255,255,255,0.96)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center", padding: "2rem", cursor: "zoom-out" }}>
          <div style={{ maxWidth: "900px", width: "100%", position: "relative" }} onClick={e => e.stopPropagation()}>
            <button onClick={() => setSelected((selected - 1 + charts.length) % charts.length)}
              style={{ position: "absolute", left: "-3rem", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", fontFamily: "'Cormorant Garamond', serif", fontSize: "2rem", color: "#888", fontWeight: 300 }}>
              ‹
            </button>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={charts[selected].file} alt={isFr ? charts[selected].labelFr : charts[selected].label} style={{ width: "100%", height: "auto", display: "block" }} />
            <div style={{ marginTop: "1rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.75rem", fontWeight: 300, color: "#888" }}>
                {isFr ? charts[selected].labelFr : charts[selected].label}
              </p>
              <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.7rem", fontWeight: 300, color: "#ccc" }}>
                {selected + 1} / {charts.length}
              </p>
            </div>
            <button onClick={() => setSelected((selected + 1) % charts.length)}
              style={{ position: "absolute", right: "-3rem", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", fontFamily: "'Cormorant Garamond', serif", fontSize: "2rem", color: "#888", fontWeight: 300 }}>
              ›
            </button>
          </div>
          <button onClick={() => setSelected(null)}
            style={{ position: "absolute", top: "2rem", right: "2rem", background: "none", border: "none", cursor: "pointer", fontFamily: "'Inter', sans-serif", fontSize: "0.75rem", fontWeight: 300, color: "#888", letterSpacing: "0.08em" }}>
            {isFr ? "fermer" : "close"}
          </button>
        </div>
      )}
    </section>
  );
}
