"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useRef, useState } from "react";
import { X, ZoomIn, ExternalLink } from "lucide-react";
import { useLang } from "@/lib/LanguageContext";

const visuals = [
  {
    file: "/visuals/01-portfolio-optimizer.png",
    project: "Portfolio Optimizer",
    projectFr: "Optimiseur de Portefeuille",
    caption: "Efficient Frontier — FAANG Portfolio, Sharpe 1.84 vs S&P 0.91",
    captionFr: "Frontière Efficiente — Portefeuille FAANG, Sharpe 1,84 vs S&P 0,91",
    accent: "#0ea5e9",
    tag: "Asset Management",
    tagFr: "Gestion d'actifs",
  },
  {
    file: "/visuals/02-lbo-model.png",
    project: "LBO Model",
    projectFr: "Modèle LBO",
    caption: "Deal Waterfall & IRR Sensitivity — Twitter/X $44Bn Acquisition",
    captionFr: "Cascade de dette & sensibilité IRR — Acquisition Twitter/X 44Mds$",
    accent: "#a78bfa",
    tag: "Private Equity",
    tagFr: "Private Equity",
  },
  {
    file: "/visuals/03-dcf-engine.png",
    project: "DCF Valuation Engine",
    projectFr: "Moteur de Valorisation DCF",
    caption: "Football Field Valuation + WACC Sensitivity — Apple Q4 2023",
    captionFr: "Valorisation Football Field + Sensibilité WACC — Apple T4 2023",
    accent: "#38bdf8",
    tag: "Corporate Finance",
    tagFr: "Finance d'entreprise",
  },
  {
    file: "/visuals/04-var-dashboard.png",
    project: "VaR Risk Dashboard",
    projectFr: "Dashboard VaR & Risques",
    caption: "P&L Loss Distribution + Monte Carlo 10K Scenarios — SVB Stress Test",
    captionFr: "Distribution des P&L + Monte Carlo 10K scénarios — Stress test SVB",
    accent: "#f43f5e",
    tag: "Risk Management",
    tagFr: "Gestion des risques",
  },
  {
    file: "/visuals/05-esg-tool.png",
    project: "ESG Scoring Tool",
    projectFr: "Outil de Scoring ESG",
    caption: "Radar & Pillar Comparison — TotalEnergies 38 vs Schneider Electric 91",
    captionFr: "Radar & comparaison par pilier — TotalEnergies 38 vs Schneider 91",
    accent: "#22c55e",
    tag: "Sustainable Finance",
    tagFr: "Finance durable",
  },
  {
    file: "/visuals/06-credit-dashboard.png",
    project: "Credit Analysis Dashboard",
    projectFr: "Dashboard Analyse Crédit",
    caption: "Altman Z-Score Timeline + Internal Rating — WeWork Distress Detection",
    captionFr: "Chronologie Z-Score + Notation interne — Détection détresse WeWork",
    accent: "#f59e0b",
    tag: "Fixed Income",
    tagFr: "Revenu fixe",
  },
];

export default function Gallery() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  const [selected, setSelected] = useState<number | null>(null);
  const { lang } = useLang();
  const isFr = lang === "fr";

  return (
    <section id="gallery" className="py-28 px-6 relative overflow-hidden" style={{ background: "linear-gradient(to bottom, #050f1a, #030712)" }}>
      <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:60px_60px]" />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[400px] pointer-events-none" style={{ background: "radial-gradient(ellipse, rgba(14,165,233,0.05) 0%, transparent 70%)" }} />

      <div className="max-w-7xl mx-auto relative z-10" ref={ref}>
        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={isInView ? { opacity: 1, y: 0 } : {}} className="mb-16">
          <p className="text-xs font-mono text-sky-400 uppercase tracking-widest mb-3">
            {isFr ? "// visuels" : "// visuals"}
          </p>
          <h2 className="text-4xl lg:text-5xl text-white tracking-tight">
            {isFr ? "Sorties visuelles" : "Visual Outputs"}
          </h2>
          <p className="text-white/40 mt-3 max-w-xl">
            {isFr
              ? "Outputs réels générés par les outils — charts, dashboards et analyses"
              : "Real outputs generated by the tools — charts, dashboards and analyses"}
          </p>
        </motion.div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
          {visuals.map((v, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 24 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              whileHover={{ y: -4 }}
              className="group cursor-pointer"
              onClick={() => setSelected(i)}
            >
              <div
                className="rounded-2xl overflow-hidden"
                style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", transition: "border-color 0.3s" }}
                onMouseEnter={e => (e.currentTarget.style.borderColor = `${v.accent}33`)}
                onMouseLeave={e => (e.currentTarget.style.borderColor = "rgba(255,255,255,0.06)")}
              >
                {/* Image */}
                <div className="relative overflow-hidden" style={{ aspectRatio: "14/8" }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={v.file}
                    alt={isFr ? v.projectFr : v.project}
                    className="w-full h-full object-cover object-top group-hover:scale-105 transition-transform duration-500"
                    style={{ filter: "brightness(0.9)" }}
                  />
                  {/* Overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-[#030712] via-transparent to-transparent opacity-60" />
                  {/* Zoom icon */}
                  <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <div className="w-12 h-12 rounded-full flex items-center justify-center backdrop-blur-sm" style={{ background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.2)" }}>
                      <ZoomIn size={20} className="text-white" />
                    </div>
                  </div>
                  {/* Tag */}
                  <div className="absolute top-3 left-3">
                    <span className="text-xs font-mono px-2.5 py-1 rounded-lg backdrop-blur-sm" style={{ background: `${v.accent}18`, border: `1px solid ${v.accent}30`, color: v.accent }}>
                      {isFr ? v.tagFr : v.tag}
                    </span>
                  </div>
                </div>

                {/* Footer */}
                <div className="p-4">
                  <h3 className="text-sm font-semibold text-white/90 mb-1">{isFr ? v.projectFr : v.project}</h3>
                  <p className="text-xs text-white/35 leading-relaxed">{isFr ? v.captionFr : v.caption}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {selected !== null && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8"
            style={{ background: "rgba(3,7,18,0.95)", backdropFilter: "blur(16px)" }}
            onClick={() => setSelected(null)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ type: "spring", damping: 25, stiffness: 300 }}
              className="relative max-w-6xl w-full"
              onClick={e => e.stopPropagation()}
            >
              {/* Close */}
              <button
                onClick={() => setSelected(null)}
                className="absolute -top-12 right-0 p-2 rounded-lg text-white/50 hover:text-white hover:bg-white/10 transition-all"
              >
                <X size={22} />
              </button>

              {/* Nav arrows */}
              <button
                onClick={() => setSelected((selected - 1 + visuals.length) % visuals.length)}
                className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-14 p-3 rounded-xl text-white/40 hover:text-white hover:bg-white/10 transition-all text-xl font-bold"
              >
                ‹
              </button>
              <button
                onClick={() => setSelected((selected + 1) % visuals.length)}
                className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-14 p-3 rounded-xl text-white/40 hover:text-white hover:bg-white/10 transition-all text-xl font-bold"
              >
                ›
              </button>

              {/* Image */}
              <div className="rounded-2xl overflow-hidden" style={{ border: `1px solid ${visuals[selected].accent}33` }}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={visuals[selected].file}
                  alt={isFr ? visuals[selected].projectFr : visuals[selected].project}
                  className="w-full h-auto"
                />
              </div>

              {/* Caption */}
              <div className="mt-4 flex items-center justify-between">
                <div>
                  <h3 className="text-white font-semibold">{isFr ? visuals[selected].projectFr : visuals[selected].project}</h3>
                  <p className="text-white/40 text-sm mt-0.5">{isFr ? visuals[selected].captionFr : visuals[selected].caption}</p>
                </div>
                <span className="text-xs font-mono text-white/25">{selected + 1} / {visuals.length}</span>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
